name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SYSTEMC_HOME: ${{ github.workspace }}/systemc-2.3.3
      LD_LIBRARY_PATH: ${{ github.workspace }}/systemc-2.3.3/lib-linux64:$LD_LIBRARY_PATH
      CPLUS_INCLUDE_PATH: ${{ github.workspace }}/systemc-2.3.3/include:$CPLUS_INCLUDE_PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make unzip wget libsfml-dev libcairo2-dev xorg cmake

      - name: Cache SystemC
        id: cache-systemc
        uses: actions/cache@v4
        with:
          path: systemc-2.3.3/build
          key: systemc-2.3.3-${{ runner.os }}-build

      - name: Install SystemC 2.3.3
        if: steps.cache-systemc.outputs.cache-hit != 'true'
        run: |
          wget https://accellera.org/images/downloads/standards/systemc/systemc-2.3.3.zip
          unzip systemc-2.3.3.zip
          cd systemc-2.3.3
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/systemc-2.3.3 \
                  -DCMAKE_INSTALL_LIBDIR=lib-linux64 \
                  -DCMAKE_CXX_STANDARD=17
          make -j$(nproc)
          make install

      - name: Cache project build
        id: cache-project
        uses: actions/cache@v4
        with:
          path: build
          key: project-build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Build repository
        run: |
          mkdir -p build && cd build
          cmake .. -DBUILD_DEBUG_TARGETS=OFF -DSYSTEMC_HOME=${SYSTEMC_HOME} -DCMAKE_PREFIX_PATH=${SYSTEMC_HOME}
          make -j$(nproc)

      - name: Test all chores JSON files
        run: |
          set -euo pipefail

          CHORES_DIR="./llm/test/chores"
          HW_CONFIG="$CHORES_DIR/hw_config.json"
          TIMEOUT_SEC=30

          FAIL=0

          for CONFIG in "$CHORES_DIR"/*.json; do
            if [[ "$CONFIG" == "$HW_CONFIG" ]]; then
              continue
            fi

            echo "Testing $CONFIG ..."

            timeout $TIMEOUT_SEC ./build/npusim --config-file "$CONFIG" --core-config-file "$HW_CONFIG" 2>&1 | \
            awk '
            /\[CATCH_TEST\]/ { found=1; exit }
            /\[ERROR\]/ { error=1; exit }
            END { if(found) exit 0; else if(error) exit 1; else exit 0 }'

            AWK_STATUS=$?
            if [[ $AWK_STATUS -eq 0 ]]; then
              echo "PASS: $CONFIG"
            elif [[ $AWK_STATUS -eq 1 ]]; then
              echo "FAIL (error output): $CONFIG"
              FAIL=1
            else
              echo "FAIL (timeout or no [CATCH_TEST]): $CONFIG"
              FAIL=1
            fi
          done

          if [[ $FAIL -ne 0 ]]; then
            echo "Some tests failed"
            exit 1
          fi
